name: UPB Devops 2024 CICD
on:
 push:
   branches: [cicd-docker-ec2, main]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout source
       uses: actions/checkout@v4
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ vars.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build docker image
       run: docker build -t ${{ vars.DOCKER_USERNAME }}/nodejs-app .
     - name: Publish image to docker hub
       run: docker push ${{ vars.DOCKER_USERNAME }}/nodejs-app:latest
 deploy:
   needs: build
   runs-on: [self-hosted]
   steps:
     - name: Pull image from docker hub
       run: sudo docker pull ${{ vars.DOCKER_USERNAME }}/nodejs-app:latest
     - name: Delete old container
       run: sudo docker rm -f nodejs-app-container
     - name: Run docker container
       run: sudo docker run -d -p 5000:5000 --name nodejs-app-container ${{ vars.DOCKER_USERNAME }}/nodejs-app
